[versions]
kotlin = "2.1.20"

paper = "2.0.0-beta.18"
nova = "0.0.8"

yml = "0.8.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

paper = { id = "io.papermc.paperweight.userdev", version.ref = "paper" }
nova = { id = "com.undefinedcreations.nova", version.ref = "nova" }

yml = { id = "de.eldoria.plugin-yml.bukkit", version.ref = "yml" }
